<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Operations;


class CreatePaymentLinkResponse
{
	
    public string $contentType;
    
    /**
     * Invalid body content
     * 
     * @var ?\Bridge\Bridgeapi\Models\Shared\InvalidBodyContent $invalidBodyContent
     */
	
    public ?\Bridge\Bridgeapi\Models\Shared\InvalidBodyContent $invalidBodyContent = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Successfully created a payment link
     * 
     * @var ?\Bridge\Bridgeapi\Models\Operations\CreatePaymentLink200ApplicationJSON $createPaymentLink200ApplicationJSONObject
     */
	
    public ?CreatePaymentLink200ApplicationJSON $createPaymentLink200ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->invalidBodyContent = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->createPaymentLink200ApplicationJSONObject = null;
	}
}
