<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Operations;

use \Bridge\Bridgeapi\Utils\SpeakeasyMetadata;
class GetPaymentLinkRequest
{
    /**
     * ID of the payment link to retrieve
     * 
     * @var string $paymentLinkID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=PaymentLinkID')]
    public string $paymentLinkID;
    
	public function __construct()
	{
		$this->paymentLinkID = "";
	}
}
