<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Operations;


class ListPaymentLinksResponse
{
	
    public string $contentType;
    
    /**
     * Invalid body content
     * 
     * @var ?\Bridge\Bridgeapi\Models\Shared\InvalidBodyContent $invalidBodyContent
     */
	
    public ?\Bridge\Bridgeapi\Models\Shared\InvalidBodyContent $invalidBodyContent = null;
    
    /**
     * OK
     * 
     * @var ?\Bridge\Bridgeapi\Models\Shared\PaymentLinksResponse $paymentLinksResponse
     */
	
    public ?\Bridge\Bridgeapi\Models\Shared\PaymentLinksResponse $paymentLinksResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->invalidBodyContent = null;
		$this->paymentLinksResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
