<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Operations;

use \Bridge\Bridgeapi\Utils\SpeakeasyMetadata;
class ListPaymentLinksRequest
{
    /**
     * Cursor pointing to the start of the desired set
     * 
     * @var ?string $after
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=after')]
    public ?string $after = null;
    
    /**
     * Number of records to return
     * 
     * @var ?int $limit
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;
    
    /**
     * Limit to payment links created after the specified date
     * 
     * @var ?\DateTime $since
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=since,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $since = null;
    
    /**
     * Filter payment links by status
     * 
     * @var ?\Bridge\Bridgeapi\Models\Operations\ListPaymentLinksStatusEnum $status
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?ListPaymentLinksStatusEnum $status = null;
    
    /**
     * Limit to transactions created before the specified date
     * 
     * @var ?\DateTime $until
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=until,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $until = null;
    
	public function __construct()
	{
		$this->after = null;
		$this->limit = null;
		$this->since = null;
		$this->status = null;
		$this->until = null;
	}
}
