<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Operations;


/** Filter payment links by status */
enum ListPaymentLinksStatus: string
{
    case VALID = 'VALID';
    case COMPLETED = 'COMPLETED';
    case EXPIRED = 'EXPIRED';
    case REVOKED = 'REVOKED';
}
