<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Shared;


class Pagination
{
	#[\JMS\Serializer\Annotation\SerializedName('next_uri')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $nextUri = null;
    
	public function __construct()
	{
		$this->nextUri = null;
	}
}
