<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Shared;


/**
 * PaymentLinkResponse - OK
 * 
 * @package Bridge\Bridgeapi\Models\Shared
 * @access public
 */
class PaymentLinkResponse
{
    /**
     * The client reference of the payment link.
     * 
     * @var ?string $clientReference
     */
	#[\JMS\Serializer\Annotation\SerializedName('client_reference')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $clientReference = null;
    
    /**
     * The creation date and time of the payment link.
     * 
     * @var ?\DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $createdAt = null;
    
    /**
     * The expiration date and time of the payment link.
     * 
     * @var ?\DateTime $expiredAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('expired_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $expiredAt = null;
    
    /**
     * The unique identifier of the payment link.
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * The URL of the payment link.
     * 
     * @var ?string $link
     */
	#[\JMS\Serializer\Annotation\SerializedName('link')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $link = null;
    
    /**
     * The status of the payment link.
     * 
     * @var ?string $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $status = null;
    
    /**
     * The transactions associated with the payment link.
     * 
     * @var ?array<\Bridge\Bridgeapi\Models\Shared\Transaction> $transactions
     */
	#[\JMS\Serializer\Annotation\SerializedName('transactions')]
    #[\JMS\Serializer\Annotation\Type('array<Bridge\Bridgeapi\Models\Shared\Transaction>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $transactions = null;
    
    /**
     * The last update date and time of the payment link.
     * 
     * @var ?\DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $updatedAt = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('Bridge\Bridgeapi\Models\Shared\User')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?User $user = null;
    
	public function __construct()
	{
		$this->clientReference = null;
		$this->createdAt = null;
		$this->expiredAt = null;
		$this->id = null;
		$this->link = null;
		$this->status = null;
		$this->transactions = null;
		$this->updatedAt = null;
		$this->user = null;
	}
}
