<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Shared;


class PaymentLinkRequest
{
	#[\JMS\Serializer\Annotation\SerializedName('bank_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $bankId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('callback_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $callbackUrl = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('client_reference')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $clientReference = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('country')]
    #[\JMS\Serializer\Annotation\Type('enum<Bridge\Bridgeapi\Models\Shared\PaymentLinkRequestCountryEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PaymentLinkRequestCountryEnum $country = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('expired_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $expiredDate = null;
    
    /**
     * $transactions
     * 
     * @var array<\Bridge\Bridgeapi\Models\Shared\Transaction> $transactions
     */
	#[\JMS\Serializer\Annotation\SerializedName('transactions')]
    #[\JMS\Serializer\Annotation\Type('array<Bridge\Bridgeapi\Models\Shared\Transaction>')]
    public array $transactions;
    
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('Bridge\Bridgeapi\Models\Shared\User')]
    public User $user;
    
	public function __construct()
	{
		$this->bankId = null;
		$this->callbackUrl = null;
		$this->clientReference = null;
		$this->country = null;
		$this->expiredDate = null;
		$this->transactions = [];
		$this->user = new \Bridge\Bridgeapi\Models\Shared\User();
	}
}
