<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Shared;


enum PaymentLinkRequestCountry: string
{
    case Fr = 'fr';
    case Es = 'es';
    case De = 'de';
    case Gb = 'gb';
}
