<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Shared;


enum PaymentLinkRequestCountry: string
{
    case FR = 'fr';
    case ES = 'es';
    case DE = 'de';
    case GB = 'gb';
}
