<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Shared;


/**
 * PaymentLinksResponse - OK
 * 
 * @package Bridge\Bridgeapi\Models\Shared
 * @access public
 */
class PaymentLinksResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('pagination')]
    #[\JMS\Serializer\Annotation\Type('Bridge\Bridgeapi\Models\Shared\Pagination')]
    public Pagination $pagination;
    
    /**
     * $resources
     * 
     * @var array<\Bridge\Bridgeapi\Models\Shared\PaymentLinkResponse> $resources
     */
	#[\JMS\Serializer\Annotation\SerializedName('resources')]
    #[\JMS\Serializer\Annotation\Type('array<Bridge\Bridgeapi\Models\Shared\PaymentLinkResponse>')]
    public array $resources;
    
	public function __construct()
	{
		$this->pagination = new \Bridge\Bridgeapi\Models\Shared\Pagination();
		$this->resources = [];
	}
}
