<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi\Models\Shared;

use \Bridge\Bridgeapi\Utils\SpeakeasyMetadata;
class Security
{
	#[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=Client-Id')]
    public ?string $clientId = null;
    
	#[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=Client-Secret')]
    public ?string $clientSecret = null;
    
	public function __construct()
	{
		$this->clientId = null;
		$this->clientSecret = null;
	}
}
