<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Bridge\Bridgeapi;

/**
 * SDK
 * 
 * @package Bridge\Bridgeapi
 * @access public
 */
class SDK
{
	public const SERVERS = [
        /** Production */
		'https://api.bridgeapi.io/v2',
	];
  	
    /**
     * Payment Links API
     * 
     * @var PaymentLinks $$paymentLinks
     */
	public PaymentLinks $paymentLinks;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return SDKBuilder
	 */
	public static function builder(): SDKBuilder
	{
		return new SDKBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->paymentLinks = new PaymentLinks($this->sdkConfiguration);
	}
}